### ISSUE TITLE
Install C Glib test dependencies in the docker image

### ISSUE THREAD

**Issue by kszucs** [ursa-labs/ursabot#174]
We can spare the test dependency installation time if we move `bundle` to the docker image instead of running it in each build.

**Comment by kou** [comment]
We can't. Because we may update test dependency in Arrow repository: https://github.com/apache/arrow/blob/master/c_glib/Gemfile

If we do it in Docker image, we need to synchronize the test dependency list in both Arrow code and CI configuration. It will increase maintenance cost.

Generally, we can use cache that can share CI job runners to improve test speed. For example:

  * Travis CI: https://docs.travis-ci.com/user/caching/#caching-directories-bundler-dependencies
  * GitLab Runner: https://docs.gitlab.com/ee/ci/caching/#caching-ruby-dependencies

**Comment by kszucs** [comment]
@kou the same applies for the rest of the builders, which is an unresolved issue yet.

We could both actually. So preinstalling the dependencies in the images (which are periodically updated) and have the dependency installation steps in the builders as well to ensure that they are up to date, but still gaining some time by the preinstallation. We could also reuse the same commands to in the images and the builders (currently we'd need to duplicate, but that's is low hanging fruit). What do you think?

**Comment by kou** [comment]
Done by apache/arrow#5589.
